int32 start #출발 여부

bool left_detected_color
bool right_detected_color
float32 lane_center_offset_color
float32 lane_angle_color

bool left_detected_cord
bool right_detected_cord
float32 lane_center_offset_cord
float32 lane_angle_cord


bool red_flag #빨간선 여부 

bool traffic_flag #신호등 여부
int32 traffic_color # 신호등 색상
bool sign_flag #표지판 여부
int32 sign_size #표지판 크기
int32 what_sign #표지판 종류
bool gate #차단기 여부
bool block #벽돌 여부
bool turn #회전 하드코딩



